/// CEC Phase 17 — Memory Provenance Lattice.
///
/// Provenance is a first-class axis alongside MemoryKind. Open-weight-generated
/// content starts in the `candidate` band — forbidden from direct correction/decision
/// writes and from promotion without a closed-loop outcome-witness.
use serde::{Serialize, Deserialize};
use crate::organ::memory_kind::MemoryKind;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize, Default)]
#[serde(rename_all = "snake_case")]
pub enum MemProvenance {
    /// Direct user input, [correction] markers, explicit human decisions.
    #[default]
    Human,
    /// Claude API output verified in-session.
    Claude,
    /// OpenAI Codex / GPT model output.
    Codex,
    /// Offline-extracted activations / probe vectors from an open-weight model (license-clean).
    OpenWeightDistilled,
    /// Text generated by an open-weight model at runtime (noisy — candidate band only).
    OpenWeightGenerated,
}

impl MemProvenance {
    pub fn from_str(s: &str) -> Self {
        match s {
            "claude"              => Self::Claude,
            "codex"               => Self::Codex,
            "ow_distilled"        => Self::OpenWeightDistilled,
            "ow_generated"        => Self::OpenWeightGenerated,
            _                     => Self::Human,
        }
    }

    pub fn label(self) -> &'static str {
        match self {
            Self::Human               => "human",
            Self::Claude              => "claude",
            Self::Codex               => "codex",
            Self::OpenWeightDistilled => "ow_distilled",
            Self::OpenWeightGenerated => "ow_generated",
        }
    }

    /// Can this provenance directly write a memory of the given kind without going
    /// through the candidate band?
    pub fn can_write_kind(self, kind: MemoryKind) -> bool {
        use MemProvenance::*; use MemoryKind::*;
        match (self, kind) {
            (Human, _)                                                   => true,
            (Claude, Thought) | (Claude, Observation) | (Claude, CodeFact) => true,
            (Codex,  Thought) | (Codex,  Observation) | (Codex,  CodeFact) => true,
            (OpenWeightDistilled, Observation) | (OpenWeightDistilled, CodeFact) => true,
            // open-weight-generated always starts in candidate band
            (OpenWeightGenerated, _) => false,
            _                        => false,
        }
    }

    /// Whether this provenance source requires an outcome-witness before any
    /// `Decision` kind write is permitted.
    pub fn requires_witness_for_decision(self) -> bool {
        !matches!(self, Self::Human)
    }
}

/// Type of outcome-witness that can promote a candidate memory.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum WitnessKind {
    /// User-supplied [correction] or explicit confirmation.
    UserCorrection,
    /// Tool-result outcome (success/fail recorded in EventTape).
    ToolResult,
    /// Router hit-rate delta improved after including this memory.
    RouterHitRateDelta,
}

impl WitnessKind {
    pub fn from_str(s: &str) -> Option<Self> {
        match s {
            "correction" | "user_correction"     => Some(Self::UserCorrection),
            "outcome" | "tool_result"             => Some(Self::ToolResult),
            "hit_rate_delta" | "router_hit_rate"  => Some(Self::RouterHitRateDelta),
            _                                     => None,
        }
    }
}
